services:
  - type: web
    name: cloud-demo
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DB_HOST
        value: ep-black-unit-a46vqcwg-pooler.us-east-1.aws.neon.tech
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_rDWQcXHV1wB4
